### PR TITLE
add missing dependencies and fix cases of imported components

### PR DESCRIPTION
**Pull request by ryanswrt**
I wasn't able to run the demo due to package import errors - fixed them up, and now it works for me, would like to know if this is a valid fix or if I'm doing something else incorrectly.

### CODE REVIEW

**Comment by arunoda** [comment]
Okay. Are you using npm@2 ?
Anyway. This is great.

**Comment by ryanswrt** [comment]
Yep, using npm 2.14

**Comment by ryanswrt** [comment]
And thanks a lot btw, finally got coffeescript react components to hot reload using storybook, after working on it for 5 or so days using other packages; can finally write Jade like templates in React without relying on another loader.

**Comment by arunoda** [comment]
Awesome. Glad you like it a lot :)
We used this with npm@3 and that's why we didn't face that issue.

We should do some testing with NPM@2.

**Pull request merged**
